apiVersion: apps/v1
kind: Deployment
metadata:
  name: ftps-dep
spec:
  selector:
    matchLabels:
      app: ftps
  template:
    metadata:
      labels:
        app: ftps
    spec:
      containers:
      - name: ftps
        image: ftps-img
        imagePullPolicy: Never
        ports:
        - containerPort: 21
          name: ftps
        - containerPort: 21000
          name: ftps-data
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - -c
            - 'pgrep telegraf && pgrep vsftpd'
          initialDelaySeconds: 10
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: ftps-svc
spec:
  selector:
    app: ftps
  ports:
    - name: ftps
      protocol: TCP
      port: 21
      targetPort: 21
    - name: ftps-data
      protocol: TCP
      port: 21000
      targetPort: 21000
  type: LoadBalancer
  loadBalancerIP: 172.17.0.5
