apiVersion: apps/v1
kind: Deployment
metadata:
  name: grafana-dep
spec:
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      containers:
      - name: grafana
        image: grafana-img
        imagePullPolicy: Never
        ports:
        - containerPort: 3000
          name: graf-port
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - -c
            - 'pgrep telegraf && pgrep grafana-server'
          initialDelaySeconds: 10
          periodSeconds: 5

apiVersion: v1
kind: Service
metadata:
  name: grafana-svc
spec:
  selector:
    app: grafana
  ports:
    - name: graf-port
      protocol: TCP
      port: 3000
      targetPort: 3000
  type: LoadBalancer
  loadBalancerIP: 172.17.0.6