apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-dep
spec:
  selector:
    matchLabels:
      app: wordpress
  template:
    metadata:
      labels:
        app: wordpress
    spec:
      containers:
      - name: wordpress
        image: wordpress-img
        imagePullPolicy: Never
        ports:
        - containerPort: 80
          name: wp-port
        livenessProbe:
          exec:
            command:
            - /bin/ash
            - -c
            - 'pgrep telegraf && pgrep php'
          initialDelaySeconds: 10
          periodSeconds: 5

apiVersion: v1
kind: Service
metadata:
  name: wordpress-svc
spec:
  selector:
    app: wordpress
  ports:
    - name: wp-port
      protocol: TCP
      port: 5050
      targetPort: 5050
  type: LoadBalancer
  loadBalancerIP: 172.17.0.3